title: Anna Bison ğŸ‡®ğŸ‡¹
description:  Computer Physicist
theme: jekyll-theme-minimal
social_links:
  - name: linkedin
    url: https://www.linkedin.com/in/annabison
  - name: email
    url: mailto:anna.bison@pm.me
